blank_issues_enabled: true
contact_links:
  - name: Join the Telegram channel
    url: https://t.me/openai_forward
    about: Join the official channel and stay tuned for news, updates and announcements.