name: ✨ Feature request

description: Suggest ideas, new features or enhancements
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I believe the idea is awesome and would benefit the framework
          required: true
        - label: I am willing to submit a PR to implement this idea.
          required: false

  - type: textarea
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the request
      placeholder: Description...
    validations:
      required: true